/**
 * PackageJsonValidator
 *
 * Validates the structure and content of package.json manifests generated by
 * CodeGeneratorService. Runs all checks in a single pass and returns every
 * failure found. No external semver library is used — validation is regex-based.
 *
 * Feature: package-json-validation
 */

import type { GeneratedFile } from '@craft/types';

// ── Regex constants ───────────────────────────────────────────────────────────

const NPM_NAME_RE = /^(@[a-z0-9-~][a-z0-9-._~]*\/)?[a-z0-9-~][a-z0-9-._~]*$/;
const SEMVER_CORE_RE = /^\d+\.\d+\.\d+$/;
const SEMVER_RANGE_RE = /^(\^|~|>=|>|<=|<)?\d+\.\d+\.\d+$/;

// ── Required field / script lists ─────────────────────────────────────────────

const REQUIRED_FIELDS = ['name', 'version', 'scripts', 'dependencies'] as const;
const REQUIRED_SCRIPTS = ['dev', 'build', 'start', 'lint'] as const;

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ValidationError {
    field: string;
    message: string;
}

export interface ValidationResult {
    valid: boolean;
    errors: ValidationError[];
}

export interface PackageManifest {
    name?: unknown;
    version?: unknown;
    private?: unknown;
    scripts?: Record<string, unknown>;
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
    [key: string]: unknown;
}

// ── PackageJsonValidator ──────────────────────────────────────────────────────

export class PackageJsonValidator {
    /**
     * Validate a GeneratedFile by parsing its JSON content first.
     * Returns a parse error if the content is not valid JSON.
     */
    validateFile(file: GeneratedFile): ValidationResult {
        let manifest: PackageManifest;
        try {
            manifest = JSON.parse(file.content) as PackageManifest;
        } catch (e: unknown) {
            const message = e instanceof Error ? e.message : String(e);
            return { valid: false, errors: [{ field: 'content', message }] };
        }
        return this.validate(manifest);
    }

    /**
     * Validate a pre-parsed PackageManifest. All checks run in a single pass.
     */
    validate(manifest: PackageManifest): ValidationResult {
        const errors: ValidationError[] = [];

        this._checkRequiredFields(manifest, errors);
        this._checkNameFormat(manifest, errors);
        this._checkVersion(manifest, errors);
        this._checkScripts(manifest, errors);
        this._checkPrivateFlag(manifest, errors);
        this._checkDependencyVersions(manifest, errors);
        this._checkNoDuplicateDeps(manifest, errors);

        return { valid: errors.length === 0, errors };
    }

    /**
     * Serialise a PackageManifest to a 2-space-indented JSON string with a
     * trailing newline.
     */
    format(manifest: PackageManifest): string {
        return JSON.stringify(manifest, null, 2) + '\n';
    }

    // ── Private check functions ───────────────────────────────────────────────

    private _checkRequiredFields(manifest: PackageManifest, errors: ValidationError[]): void {
        for (const field of REQUIRED_FIELDS) {
            if (!(field in manifest) || manifest[field] === undefined || manifest[field] === null) {
                errors.push({ field, message: `Required field "${field}" is missing` });
            }
        }
    }

    private _checkNameFormat(manifest: PackageManifest, errors: ValidationError[]): void {
        if (typeof manifest.name !== 'string' || manifest.name.length === 0) {
            // Already caught by _checkRequiredFields if absent; only add if present but wrong type
            if ('name' in manifest && manifest.name !== undefined && manifest.name !== null) {
                errors.push({ field: 'name', message: 'Package name must be a non-empty string' });
            }
            return;
        }
        if (!NPM_NAME_RE.test(manifest.name)) {
            errors.push({
                field: 'name',
                message: `Package name "${manifest.name}" does not conform to npm naming rules`,
            });
        }
    }

    private _checkVersion(manifest: PackageManifest, errors: ValidationError[]): void {
        if (typeof manifest.version !== 'string') {
            if ('version' in manifest && manifest.version !== undefined && manifest.version !== null) {
                errors.push({ field: 'version', message: 'Version must be a string' });
            }
            return;
        }
        if (!SEMVER_CORE_RE.test(manifest.version)) {
            errors.push({
                field: 'version',
                message: `Version "${manifest.version}" is not a valid semver string (expected MAJOR.MINOR.PATCH)`,
            });
        }
    }

    private _checkScripts(manifest: PackageManifest, errors: ValidationError[]): void {
        if (!manifest.scripts || typeof manifest.scripts !== 'object' || Array.isArray(manifest.scripts)) {
            if ('scripts' in manifest && manifest.scripts !== undefined && manifest.scripts !== null) {
                errors.push({ field: 'scripts', message: 'scripts must be an object' });
            }
            return;
        }
        for (const key of REQUIRED_SCRIPTS) {
            if (!(key in manifest.scripts)) {
                errors.push({
                    field: `scripts.${key}`,
                    message: `Required script "${key}" is missing`,
                });
            }
        }
    }

    private _checkPrivateFlag(manifest: PackageManifest, errors: ValidationError[]): void {
        if (manifest.private !== true) {
            errors.push({
                field: 'private',
                message: 'The "private" field must be set to true to prevent accidental npm publishes',
            });
        }
    }

    private _checkDependencyVersions(manifest: PackageManifest, errors: ValidationError[]): void {
        const depGroups: Array<[string, Record<string, string> | undefined]> = [
            ['dependencies', manifest.dependencies],
            ['devDependencies', manifest.devDependencies],
        ];

        for (const [groupName, deps] of depGroups) {
            if (!deps || typeof deps !== 'object') continue;
            for (const [pkgName, version] of Object.entries(deps)) {
                if (typeof version !== 'string' || !SEMVER_RANGE_RE.test(version)) {
                    errors.push({
                        field: `${groupName}/${pkgName}`,
                        message: `Version "${version}" for "${pkgName}" is not a valid semver range`,
                    });
                }
            }
        }
    }

    private _checkNoDuplicateDeps(manifest: PackageManifest, errors: ValidationError[]): void {
        if (!manifest.dependencies || !manifest.devDependencies) return;
        for (const pkgName of Object.keys(manifest.dependencies)) {
            if (pkgName in manifest.devDependencies) {
                errors.push({
                    field: `dependencies/${pkgName}`,
                    message: `"${pkgName}" is declared in both dependencies and devDependencies`,
                });
            }
        }
    }
}

// Export singleton instance
export const packageJsonValidator = new PackageJsonValidator();
